version: '3.8'

services:
  backend:
    container_name: django
    domainname: backend
    build:
      context: ./
      dockerfile: Dockerfile
    healthcheck:
      test: curl -f http://0.0.0.0:8000/api/v1 || exit 1
      interval: 5s
      retries: 10
      start_period: 15s
      timeout: 10s
    ports:
      - 8000:8000
    volumes:
      - static_volume:/home/app/web/static
      - log_volume:/home/app/web/logs
    env_file:
      - ./.env
    profiles: ['dev', 'test']
    depends_on:
      - database
  
  cron:
    container_name: celery-beat
    build: .
    entrypoint: celery -A racks beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - backups_volume:/home/app/web/backup
    env_file:
      - ./.env
    profiles: ['dev', 'test']
    depends_on:
      backend:
        condition: service_healthy
      message-broker:
        condition: service_started
      worker:
        condition: service_started

  worker:
    container_name: celery-worker
    build: .
    entrypoint: celery -A racks worker -l INFO
    volumes:
      - backups_volume:/home/app/web/backup
    env_file:
      - ./.env
    profiles: ['dev', 'test']
    depends_on:
      backend:
        condition: service_healthy
      message-broker:
        condition: service_started
  
  message-broker:
    container_name: redis
    image: redis:6.2.7-alpine
    profiles: ['dev', 'test']

  database:
    container_name: postgres
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    profiles: ['dev', 'test']

  frontend:
    container_name: vue
    domainname: frontend
    build:
      context: ./racks_frontend
      dockerfile: Dockerfile
    healthcheck:
      test: curl -f http://0.0.0.0:8080 || exit 1
      interval: 5s
      retries: 10
      start_period: 15s
      timeout: 10s
    volumes:
      - vue_dist:/app/dist
    ports:
      - 8080:8080
    profiles: ['dev', 'test']
    depends_on:
      - backend
      
  web-server:
    container_name: nginx
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - static_volume:/home/app/web/static
      - vue_dist:/app/dist
    profiles: ['dev', 'test']
    depends_on:
      - backend
      - frontend

  selenium:
    container_name: chrome
    image: selenium/standalone-chrome
    extra_hosts:
      - host.docker.internal:host-gateway
    env_file:
      - ./.env
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - 4444:4444
    profiles: ['test']
    depends_on:
      - frontend
      - backend
  
  test-runner:
    container_name: e2e_tests
    build:
      context: ./e2e_tests
      dockerfile: Dockerfile
    command: python e2e_tests.py
    env_file:
      - ./.env
    volumes:
      - test_results:/home/app/test/test_results
    profiles: ['test']
    depends_on:
      backend:
        condition: service_healthy
      frontend:
        condition: service_healthy
      selenium:
        condition: service_started


volumes:
  postgres_data:
  static_volume:
  log_volume:
  backups_volume:
  test_results:
  vue_dist: